### ISSUE TITLE
What do you do when the recaptcha is wrong?

### ISSUE THREAD

**Issue by nishantpant** [jgdevlabs/aspnetcore-recaptcha#6]
Thanks for writing this package. I added it to my code and it shows up and seems to be working. However, when I submit my form without pressing "I am not a robot" the form submits anyway.. and comes back with a 404 error. There is no error on the screen to tell the user they should have checked the box before submitting.

**Comment by jooni91** [comment]
Unfortunately at the moment, the package does not provide any out of the box frontend validation for this case. You could all thou configure the service not to block bad requests either globally or action specifically and do the validation in your controller action (backend).

For example:

**Global configuration**

In your `Startup.cs` file at service registration
```csharp
services.AddRecaptchaService(conf => 
{
    conf.ValidationFailedAction = ValidationFailedAction.ContinueRequest;
});
```

**Local configuration**

```csharp
public class MyController : Controller
{
    [ValidateRecaptcha(ValidationFailedAction = ValidationFailedAction.ContinueRequest)]
    public IActionResult MyAction()
    {
        // some code
    }
}
```

Now for the validation part, we would modify our `MyAction` method in the following ways. First, add a new parameter to it of type `ValidationResponse`. This will be automatically injected as an argument by the service.

The model has a property called `Success`, which would also return **false** in case that the user did not complete the ReCaptcha challenge.

So as an example of what the action method could look like:

```csharp
public IActionResult MyAction(ValidationResponse validationResponse)
{
    if (!validationResponse.Success)
    {
        ModelState.AddModelError("recaptcha", "Please complete the reCAPTCHA challenge.");
        return Ok();
    }

    // Code if challenge completed successful here
}
```

Don't forget to add the validation error label to your view, like:

```razor
<recaptcha />
@Html.ValidationMessage("recaptcha")
```

Hopefully, this answers your question. I'm sorry that you have to take these extra steps for validation to work. 
I might soon try to make this whole validation stuff more convenient for developers, but I can not promise yet when this is going to happen.

**Comment by nishantpant** [comment]
I greatly appreciate your quick and very detailed explanation. Thank you so
much.

**Comment by jooni91** [comment]
I will close this issue as I assume that it is solved now. 

I will take note of this and as I stated at the end of my comment above, I will try to make validation more convenient in the future.
Feel free to reopen this issue if my assumption was wrong and you still have unanswered questions about this topic. :slightly_smiling_face:
